#!/usr/bin/env python3

import re
import sys

pid_mappings = {}
next_pid = 100

for line in sys.stdin:
    tokens = re.split(r"\s+", line)

    new_ppid = pid_mappings.get(tokens[4])
    if new_ppid is None:
        new_ppid = next_pid
        pid_mappings[tokens[4]] = new_ppid
        next_pid += 1
    tokens[4] = str(new_ppid)

    new_pid = pid_mappings.get(tokens[2])
    if new_pid is None:
        new_pid = next_pid
        pid_mappings[tokens[2]] = new_pid
        next_pid += 1
    tokens[2] = str(new_pid)

    print(" ".join(tokens))
